from enum import Enum

class DialogActTypes(Enum):
    UNDEFINED = 1
    HELLO = 2
    GOODBYE = 3
    INFORM = 4
    REQUEST = 5
    REQALTS = 6
    CONFIRM = 7
    DENY = 8
    MAKE_PIZZA = 9
    ADD_MODALITY = 10
    GREET = 11
    ADD_PERSONAL = 12
    ORDER_PREFERRED = 13
    CHECK_ORDER_STATUS = 14
    THANK = 15
    UPDATE_MODALITY = 16
    ADD_ATTRIBUTE = 17
    ADD_PAYMENT_ATTRIBUTE = 18
    ADD_TO_ORDER = 19
    DEPART = 20
    END_ORDERING = 21
    MODIFY_ORDER_MODALITY = 22
    MODIFY_PREFERRED_ORDER = 23
    REMOVE_ATTRIBUTE = 24
    REQUEST_COST_OF = 25
    REQUEST_LISTING = 26
    START_ORDERING = 27
    UPDATE = 28
    UPDATE_ATTRIBUTE = 29
    UPDATE_PAYMENT_ATTRIBUTE = 30
    UPDATE_PERSONAL = 31